spring:
  application:
    name: Ouath2 Demo
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 394711724432-0ljm40bg0p1acis0vpo85blrog9bts8h.apps.googleusercontent.com
            client-secret: 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
          svipe:
            client-id: 8a9b0e61-b542-4b69-abb3-57c2c761b4e2
            client-secret: 74ffd70b-670b-41b7-9a3a-0eb3fcf8e853
          github:
            client-id: 55142bcd615fb361054f
            client-secret: 92bd967861dd945aaf89e303fb8678498c06d76c

        provider:
          google:
            issuer-uri: https://accounts.google.com
          svipe:
            issuer-uri: https://api.svipe.com/oidc/v1

logging:
  level:
    org.springframework.security: DEBUG
